### PR TITLE
Fixed spelling of organization

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
I did the change with search&replace, so I just open this PR for reference. If this code is already in the autoupdate service, and this repo can be closed, just close this PR.

### CODE REVIEW

**Comment by ostcar** [comment]
The autoupdate service does not need this repo anymore. If it needed by the backend?

**Comment by FinnStutzenstein** [comment]
The permission service was just removed: https://github.com/OpenSlides/openslides-backend/pull/731

**Comment by FinnStutzenstein** [comment]
Can this repo be closed then?

**Comment by ostcar** [comment]
Yes. I will do this

**Pull request closed without merging**
